-- Creating table for Country Codes
CREATE TABLE countries(
    country_id int GENERATED BY DEFAULT AS IDENTITY,
    country_code VARCHAR(4) NOT NULL,
    ECONOMY VARCHAR(40) NOT NULL,
    Region VARCHAR(40) NOT NULL
  
);

-- Creating table for Productive Capacities
CREATE TABLE prod_cap(
    prod_cap_id int GENERATED BY DEFAULT AS IDENTITY,
    country_code VARCHAR(4) NOT NULL,
    YEARS INT NOT NULL,
    productivity_over_index FLOAT NOT NULL,
    human_capital FLOAT NOT NULL,
    natural_capacity FLOAT NOT NULL,
    energy FLOAT NOT NULL,
    transport FLOAT NOT NULL,
    info_comm_tech FLOAT NOT NULL,
    institutions FLOAT NOT NULL,
    private_sector FLOAT NOT NULL,
    structural_change FLOAT NOT NULL
);

-- Creating table for GDP
CREATE TABLE GDP(
    GDP_id int GENERATED BY DEFAULT AS IDENTITY,
    country_code VARCHAR(4) NOT NULL,
    YEARS INT NOT NULL,
    GDP_USdollars_millions FLOAT NOT NULL,
    GDP_per_capita_Usdollars FLOAT NOT NULL
);
-- Creating table for Frontier Technology
CREATE TABLE frontier_tech(
    frontier_tech_id int GENERATED BY DEFAULT AS IDENTITY,
    country_code VARCHAR(4) NOT NULL,
    YEARS INT NOT NULL,
    tech_overall_index FLOAT NOT NULL,
    ICT FLOAT NOT NULL,
    skills FLOAT NOT NULL,
    research_dev FLOAT NOT NULL,
    Industry_activity FLOAT NOT NULL,
    finance_access FLOAT NOT NULL
);
